version: '3.1'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=tusharsinnghkumar04
      - N8N_BASIC_AUTH_PASSWORD=Tushar@2002
      - WEBHOOK_URL=https://leadgenerator-a9fi.onrender.com/
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_ENCRYPTION_KEY=thisisaverysecurekey
    volumes:
      - ~/.n8n:/home/node/.n8n
    env_file:
      - env.env